name: context_extensions
description: Various extensions on BuildContext to access inherited widget's state
version: 0.1.0
author: aligator <ali.gh2236@gmail.com>
homepage: https://aligator.ir

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: